CREATE TABLE `minions`
(`id` INT NOT NULL AUTO_INCREMENT,
`name` VARCHAR(50) NULL,
`age` INT NOT NULL,
PRIMARY KEY (`id`)
);

CREATE TABLE `towns`
(`town_id` INT NOT NULL AUTO_INCREMENT,
`name` VARCHAR(50) NOT NULL,
PRIMARY KEY (`town_id`)
);