ALTER TABLE `users`
	MODIFY `id` INT UNIQUE,
	DROP PRIMARY KEY;

ALTER TABLE `users`
	ADD PRIMARY KEY (`id`),
	MODIFY `id` INT UNIQUE AUTO_INCREMENT;

ALTER TABLE `users`
	MODIFY `username` VARCHAR(30) UNIQUE;